version: '2.1'
orbs:
  node: circleci/node@lts

jobs:
  coveralls:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run coveralls


workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                # - "node"
                - 18.16.1
                - 16.20.1
                - 12.22.12
                - 10.24.1
                - 8.17.0
                # - 6.17.1 # not support
      - coveralls