version: 2.1
orbs:
  node: circleci/node@4.1
workflows:
  version: 2
  build:
    jobs:
      - node/test:
          version: 'latest'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          version: '10'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          version: '8'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          version: '6'
          # filters:
          #   branches:
          #     only: master
jobs:
  coveralls:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm run coveralls
