version: 2.1

orbs:
  node: circleci/node@5.0.2

executors:
  node-executor:
    docker:
      - image: cimg/node:lts

jobs:
  build_and_test:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages
      - run:
        command: npm run coverage


  # coveralls:
  #   executor: node-executor
  #   steps:
  #     - checkout
  #     - node/install-packages
  #     - run: 
  #       command: npm run coveralls
  #       name: coveralls

workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 6
                - 8
                - 10
                - "latest"