version: 2.1
orbs:
  node: circleci/node@4.1
executors:
  node-executor:
    docker:
      - image: cimg/node:lts
workflows:
  version: 2
  build-and-coveralls:
    jobs:
      - node/test:
          name: test-node-latest
          executor: node-executor
          version: 'latest'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          name: test-node-10
          executor: node-executor
          version: '10'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          name: test-node-8
          executor: node-executor
          version: '8'
          # filters:
          #   branches:
          #     only: master
      - node/test:
          name: test-node-6
          executor: node-executor
          version: '6'
          # filters:
          #   branches:
          #     only: master
      - coveralls
jobs:
  coveralls:
    executor: node-executor
    steps:
      - checkout
      - node/install-packages
      - run: npm run coveralls
