version: '2.1'
orbs:
  node: circleci/node@5.1.0
workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                # - "node"
                - 18
                - 16
                - 12
                - 10
                - 8
                - 6